-- ================================================================
-- Index UNIQUE: categories_slug_key on catalog.categories
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX categories_slug_key ON catalog.categories USING btree (slug);
