-- ================================================================
-- Index: idx_reviews_user on commerce.reviews
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_reviews_user ON commerce.reviews USING btree (user_id);
