-- ================================================================
-- Index: idx_reviews_product on commerce.reviews
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_reviews_product ON commerce.reviews USING btree (product_id, status);
