-- ================================================================
-- Index UNIQUE: reviews_product_id_user_id_order_item_id_key on commerce.reviews
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX reviews_product_id_user_id_order_item_id_key ON commerce.reviews USING btree (product_id, user_id, order_item_id);
