-- ================================================================
-- Index: idx_cart_session on commerce.shopping_carts
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_cart_session ON commerce.shopping_carts USING btree (session_id);
