-- ================================================================
-- Index UNIQUE: tags_slug_key on catalog.tags
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX tags_slug_key ON catalog.tags USING btree (slug);
