-- ================================================================
-- Index UNIQUE: tags_name_key on catalog.tags
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX tags_name_key ON catalog.tags USING btree (name);
