-- ================================================================
-- Index: idx_orders_user on commerce.orders
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_orders_user ON commerce.orders USING btree (user_id, created_at DESC);
