-- ================================================================
-- Index: idx_orders_created on commerce.orders
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_orders_created ON commerce.orders USING btree (created_at DESC);
