-- ================================================================
-- Index: idx_orders_number on commerce.orders
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_orders_number ON commerce.orders USING btree (order_number);
