-- ================================================================
-- Index UNIQUE: orders_order_number_key on commerce.orders
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX orders_order_number_key ON commerce.orders USING btree (order_number);
