-- ================================================================
-- Index UNIQUE: cart_items_cart_id_variant_id_key on commerce.cart_items
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX cart_items_cart_id_variant_id_key ON commerce.cart_items USING btree (cart_id, variant_id);
