-- ================================================================
-- Index: idx_addresses_user on identity.addresses
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_addresses_user ON identity.addresses USING btree (user_id);
