-- ================================================================
-- Index: idx_users_active on identity.users
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_users_active ON identity.users USING btree (is_active) WHERE (is_active = true);
