-- ================================================================
-- Index: idx_users_deleted on identity.users
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_users_deleted ON identity.users USING btree (deleted_at) WHERE (deleted_at IS NULL);
