-- ================================================================
-- Index: idx_users_email on identity.users
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_users_email ON identity.users USING btree (email);
