-- ================================================================
-- Index UNIQUE: users_phone_key on identity.users
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX users_phone_key ON identity.users USING btree (phone);
