-- ================================================================
-- Index UNIQUE: users_email_key on identity.users
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX users_email_key ON identity.users USING btree (email);
