-- ================================================================
-- Index UNIQUE: roles_name_key on identity.roles
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX roles_name_key ON identity.roles USING btree (name);
