-- ================================================================
-- Index: idx_inventory_low on catalog.inventory
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_inventory_low ON catalog.inventory USING btree (qty_available) WHERE (qty_available <= reorder_point);
