-- ================================================================
-- Index UNIQUE: inventory_variant_id_key on catalog.inventory
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX inventory_variant_id_key ON catalog.inventory USING btree (variant_id);
