-- ================================================================
-- Table: catalog.attribute_types
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."attribute_types" (
    "id" smallint NOT NULL DEFAULT nextval('catalog.attribute_types_id_seq'::regclass),
    "name" variant_type NOT NULL,
    "label" character varying(50) NOT NULL,
    CONSTRAINT "attribute_types_pkey" PRIMARY KEY (id),
    CONSTRAINT "attribute_types_name_key" UNIQUE (name)
);
