-- ================================================================
-- Table: catalog.brands
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."brands" (
    "id" integer NOT NULL DEFAULT nextval('catalog.brands_id_seq'::regclass),
    "name" character varying(150) NOT NULL,
    "slug" character varying(150) NOT NULL,
    "logo_url" text,
    "website" text,
    "description" text,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "brands_pkey" PRIMARY KEY (id),
    CONSTRAINT "brands_name_key" UNIQUE (name),
    CONSTRAINT "brands_slug_key" UNIQUE (slug)
);
