-- ================================================================
-- Table: catalog.categories
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."categories" (
    "id" integer NOT NULL DEFAULT nextval('catalog.categories_id_seq'::regclass),
    "parent_id" integer,
    "name" character varying(150) NOT NULL,
    "slug" character varying(150) NOT NULL,
    "description" text,
    "image_url" text,
    "sort_order" smallint NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "path" text DEFAULT ((COALESCE((parent_id)::text, ''::text) || '/'::text) || (id)::text),
    CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES catalog.categories(id),
    CONSTRAINT "categories_pkey" PRIMARY KEY (id),
    CONSTRAINT "categories_slug_key" UNIQUE (slug)
);
