-- ================================================================
-- Table: catalog.inventory
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."inventory" (
    "id" integer NOT NULL DEFAULT nextval('catalog.inventory_id_seq'::regclass),
    "variant_id" uuid NOT NULL,
    "qty_on_hand" integer NOT NULL DEFAULT 0,
    "qty_reserved" integer NOT NULL DEFAULT 0,
    "qty_available" integer DEFAULT (qty_on_hand - qty_reserved),
    "reorder_point" integer NOT NULL DEFAULT 5,
    "reorder_qty" integer NOT NULL DEFAULT 50,
    "warehouse_location" character varying(50),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "inventory_qty_on_hand_check" CHECK (qty_on_hand >= 0),
    CONSTRAINT "inventory_qty_reserved_check" CHECK (qty_reserved >= 0),
    CONSTRAINT "inventory_variant_id_fkey" FOREIGN KEY (variant_id) REFERENCES catalog.product_variants(id) ON DELETE CASCADE,
    CONSTRAINT "inventory_pkey" PRIMARY KEY (id),
    CONSTRAINT "inventory_variant_id_key" UNIQUE (variant_id)
);
