-- ================================================================
-- Table: catalog.product_images
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."product_images" (
    "id" integer NOT NULL DEFAULT nextval('catalog.product_images_id_seq'::regclass),
    "product_id" uuid NOT NULL,
    "url" text NOT NULL,
    "alt_text" character varying(255),
    "sort_order" smallint NOT NULL DEFAULT 0,
    "is_primary" boolean NOT NULL DEFAULT false,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "product_images_product_id_fkey" FOREIGN KEY (product_id) REFERENCES catalog.products(id) ON DELETE CASCADE,
    CONSTRAINT "product_images_pkey" PRIMARY KEY (id)
);
