-- ================================================================
-- Table: catalog.product_variants
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."product_variants" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "product_id" uuid NOT NULL,
    "sku" character varying(100) NOT NULL,
    "name" character varying(255) NOT NULL,
    "attributes" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "price_modifier" numeric(12,2) NOT NULL DEFAULT 0,
    "weight_grams" integer,
    "barcode" character varying(100),
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "product_variants_product_id_fkey" FOREIGN KEY (product_id) REFERENCES catalog.products(id) ON DELETE CASCADE,
    CONSTRAINT "product_variants_pkey" PRIMARY KEY (id),
    CONSTRAINT "product_variants_sku_key" UNIQUE (sku)
);
