-- ================================================================
-- Table: catalog.products
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."products" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "brand_id" integer,
    "category_id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "slug" character varying(255) NOT NULL,
    "sku" character varying(100) NOT NULL,
    "description" text,
    "short_desc" character varying(500),
    "base_price" numeric(12,2) NOT NULL,
    "compare_price" numeric(12,2),
    "cost_price" numeric(12,2),
    "weight_grams" integer,
    "is_active" boolean NOT NULL DEFAULT true,
    "is_featured" boolean NOT NULL DEFAULT false,
    "is_digital" boolean NOT NULL DEFAULT false,
    "meta_title" character varying(255),
    "meta_description" character varying(500),
    "search_vector" tsvector DEFAULT to_tsvector('english'::regconfig, (((((COALESCE(name, ''::character varying))::text || ' '::text) || (COALESCE(short_desc, ''::character varying))::text) || ' '::text) || COALESCE(description, ''::text))),
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    "published_at" timestamp with time zone,
    "deleted_at" timestamp with time zone,
    CONSTRAINT "products_base_price_check" CHECK (base_price >= 0::numeric),
    CONSTRAINT "products_compare_price_check" CHECK (compare_price >= 0::numeric),
    CONSTRAINT "products_cost_price_check" CHECK (cost_price >= 0::numeric),
    CONSTRAINT "products_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES catalog.brands(id),
    CONSTRAINT "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES catalog.categories(id),
    CONSTRAINT "products_pkey" PRIMARY KEY (id),
    CONSTRAINT "products_sku_key" UNIQUE (sku),
    CONSTRAINT "products_slug_key" UNIQUE (slug)
);
