-- ================================================================
-- Table: catalog.product_tags
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."product_tags" (
    "product_id" uuid NOT NULL,
    "tag_id" integer NOT NULL,
    CONSTRAINT "product_tags_product_id_fkey" FOREIGN KEY (product_id) REFERENCES catalog.products(id) ON DELETE CASCADE,
    CONSTRAINT "product_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES catalog.tags(id) ON DELETE CASCADE,
    CONSTRAINT "product_tags_pkey" PRIMARY KEY (product_id, tag_id)
);
