-- ================================================================
-- Table: catalog.tags
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."tags" (
    "id" integer NOT NULL DEFAULT nextval('catalog.tags_id_seq'::regclass),
    "name" character varying(50) NOT NULL,
    "slug" character varying(50) NOT NULL,
    CONSTRAINT "tags_pkey" PRIMARY KEY (id),
    CONSTRAINT "tags_name_key" UNIQUE (name),
    CONSTRAINT "tags_slug_key" UNIQUE (slug)
);
