-- ================================================================
-- Table: catalog.v_product_summary
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "catalog"."v_product_summary" (
    "id" uuid,
    "name" character varying(255),
    "slug" character varying(255),
    "sku" character varying(100),
    "base_price" numeric(12,2),
    "compare_price" numeric(12,2),
    "brand" character varying(150),
    "category" character varying(150),
    "variant_count" bigint,
    "total_qty_available" bigint,
    "avg_rating" numeric,
    "review_count" bigint,
    "primary_image" text
);
