-- ================================================================
-- Table: commerce.cart_items
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."cart_items" (
    "id" integer NOT NULL DEFAULT nextval('commerce.cart_items_id_seq'::regclass),
    "cart_id" uuid NOT NULL,
    "variant_id" uuid NOT NULL,
    "quantity" smallint NOT NULL,
    "unit_price" numeric(12,2) NOT NULL,
    "added_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "cart_items_quantity_check" CHECK (quantity > 0),
    CONSTRAINT "cart_items_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES commerce.shopping_carts(id) ON DELETE CASCADE,
    CONSTRAINT "cart_items_variant_id_fkey" FOREIGN KEY (variant_id) REFERENCES catalog.product_variants(id),
    CONSTRAINT "cart_items_pkey" PRIMARY KEY (id),
    CONSTRAINT "cart_items_cart_id_variant_id_key" UNIQUE (cart_id, variant_id)
);
