-- ================================================================
-- Table: commerce.coupons
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."coupons" (
    "id" integer NOT NULL DEFAULT nextval('commerce.coupons_id_seq'::regclass),
    "code" character varying(50) NOT NULL,
    "description" character varying(255),
    "discount_type" discount_type NOT NULL,
    "discount_value" numeric(12,2) NOT NULL,
    "min_order_amount" numeric(12,2),
    "max_discount_amount" numeric(12,2),
    "usage_limit" integer,
    "used_count" integer NOT NULL DEFAULT 0,
    "per_user_limit" smallint NOT NULL DEFAULT 1,
    "is_active" boolean NOT NULL DEFAULT true,
    "starts_at" timestamp with time zone NOT NULL DEFAULT now(),
    "expires_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "coupons_discount_value_check" CHECK (discount_value > 0::numeric),
    CONSTRAINT "coupons_pkey" PRIMARY KEY (id),
    CONSTRAINT "coupons_code_key" UNIQUE (code)
);
