-- ================================================================
-- Table: commerce.order_items
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."order_items" (
    "id" integer NOT NULL DEFAULT nextval('commerce.order_items_id_seq'::regclass),
    "order_id" uuid NOT NULL,
    "variant_id" uuid NOT NULL,
    "product_name" character varying(255) NOT NULL,
    "variant_name" character varying(255) NOT NULL,
    "sku" character varying(100) NOT NULL,
    "quantity" integer NOT NULL,
    "unit_price" numeric(12,2) NOT NULL,
    "total_price" numeric(12,2) DEFAULT ((quantity)::numeric * unit_price),
    "tax_rate" numeric(5,4) NOT NULL DEFAULT 0,
    "attributes" jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT "order_items_quantity_check" CHECK (quantity > 0),
    CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES commerce.orders(id) ON DELETE RESTRICT,
    CONSTRAINT "order_items_variant_id_fkey" FOREIGN KEY (variant_id) REFERENCES catalog.product_variants(id),
    CONSTRAINT "order_items_pkey" PRIMARY KEY (id)
);
