-- ================================================================
-- Table: commerce.orders
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."orders" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "user_id" uuid NOT NULL,
    "shipping_address_id" uuid NOT NULL,
    "billing_address_id" uuid NOT NULL,
    "shipping_method_id" integer,
    "coupon_id" integer,
    "order_number" character varying(30) NOT NULL,
    "status" order_status NOT NULL DEFAULT 'pending'::order_status,
    "subtotal" numeric(12,2) NOT NULL,
    "discount_amount" numeric(12,2) NOT NULL DEFAULT 0,
    "shipping_cost" numeric(12,2) NOT NULL DEFAULT 0,
    "tax_amount" numeric(12,2) NOT NULL DEFAULT 0,
    "total_amount" numeric(12,2) NOT NULL,
    "currency" character(3) NOT NULL DEFAULT 'USD'::bpchar,
    "notes" text,
    "ip_address" inet,
    "user_agent" text,
    "tracking_number" character varying(100),
    "shipped_at" timestamp with time zone,
    "delivered_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "cancellation_reason" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "chk_total" CHECK (total_amount = (subtotal - discount_amount + shipping_cost + tax_amount)),
    CONSTRAINT "orders_billing_address_id_fkey" FOREIGN KEY (billing_address_id) REFERENCES identity.addresses(id),
    CONSTRAINT "orders_coupon_id_fkey" FOREIGN KEY (coupon_id) REFERENCES commerce.coupons(id),
    CONSTRAINT "orders_shipping_address_id_fkey" FOREIGN KEY (shipping_address_id) REFERENCES identity.addresses(id),
    CONSTRAINT "orders_shipping_method_id_fkey" FOREIGN KEY (shipping_method_id) REFERENCES commerce.shipping_methods(id),
    CONSTRAINT "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES identity.users(id),
    CONSTRAINT "orders_pkey" PRIMARY KEY (id),
    CONSTRAINT "orders_order_number_key" UNIQUE (order_number)
);
