-- ================================================================
-- Table: commerce.payments
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."payments" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "order_id" uuid NOT NULL,
    "method" payment_method NOT NULL,
    "status" payment_status NOT NULL DEFAULT 'pending'::payment_status,
    "amount" numeric(12,2) NOT NULL,
    "currency" character(3) NOT NULL DEFAULT 'USD'::bpchar,
    "gateway" character varying(50),
    "gateway_txn_id" character varying(255),
    "gateway_response" jsonb,
    "refunded_amount" numeric(12,2) NOT NULL DEFAULT 0,
    "processed_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "payments_amount_check" CHECK (amount > 0::numeric),
    CONSTRAINT "payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES commerce.orders(id),
    CONSTRAINT "payments_pkey" PRIMARY KEY (id)
);
