-- ================================================================
-- Table: commerce.reviews
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."reviews" (
    "id" integer NOT NULL DEFAULT nextval('commerce.reviews_id_seq'::regclass),
    "product_id" uuid NOT NULL,
    "user_id" uuid NOT NULL,
    "order_item_id" integer,
    "rating" smallint NOT NULL,
    "title" character varying(200),
    "body" text,
    "status" review_status NOT NULL DEFAULT 'pending'::review_status,
    "helpful_count" integer NOT NULL DEFAULT 0,
    "is_verified" boolean NOT NULL DEFAULT false,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "reviews_rating_check" CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT "reviews_order_item_id_fkey" FOREIGN KEY (order_item_id) REFERENCES commerce.order_items(id),
    CONSTRAINT "reviews_product_id_fkey" FOREIGN KEY (product_id) REFERENCES catalog.products(id) ON DELETE CASCADE,
    CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES identity.users(id),
    CONSTRAINT "reviews_pkey" PRIMARY KEY (id),
    CONSTRAINT "reviews_product_id_user_id_order_item_id_key" UNIQUE (product_id, user_id, order_item_id)
);
