-- ================================================================
-- Table: commerce.shipping_methods
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."shipping_methods" (
    "id" integer NOT NULL DEFAULT nextval('commerce.shipping_methods_id_seq'::regclass),
    "name" character varying(100) NOT NULL,
    "carrier" character varying(100),
    "estimated_days" numrange,
    "base_cost" numeric(10,2) NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT true,
    CONSTRAINT "shipping_methods_pkey" PRIMARY KEY (id)
);
