-- ================================================================
-- Table: commerce.shopping_carts
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."shopping_carts" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "user_id" uuid,
    "session_id" character varying(128),
    "coupon_id" integer,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    "expires_at" timestamp with time zone NOT NULL DEFAULT (now() + '30 days'::interval),
    CONSTRAINT "chk_cart_owner" CHECK (user_id IS NOT NULL OR session_id IS NOT NULL),
    CONSTRAINT "shopping_carts_coupon_id_fkey" FOREIGN KEY (coupon_id) REFERENCES commerce.coupons(id),
    CONSTRAINT "shopping_carts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
    CONSTRAINT "shopping_carts_pkey" PRIMARY KEY (id)
);
