-- ================================================================
-- Table: commerce.v_order_summary
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."v_order_summary" (
    "id" uuid,
    "order_number" character varying(30),
    "status" order_status,
    "total_amount" numeric(12,2),
    "currency" character(3),
    "created_at" timestamp with time zone,
    "email" citext,
    "customer_name" text,
    "item_count" bigint,
    "payment_status" payment_status,
    "payment_method" payment_method
);
