-- ================================================================
-- Table: commerce.wishlists
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "commerce"."wishlists" (
    "id" integer NOT NULL DEFAULT nextval('commerce.wishlists_id_seq'::regclass),
    "user_id" uuid NOT NULL,
    "product_id" uuid NOT NULL,
    "variant_id" uuid,
    "notes" text,
    "added_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "wishlists_product_id_fkey" FOREIGN KEY (product_id) REFERENCES catalog.products(id) ON DELETE CASCADE,
    CONSTRAINT "wishlists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
    CONSTRAINT "wishlists_variant_id_fkey" FOREIGN KEY (variant_id) REFERENCES catalog.product_variants(id),
    CONSTRAINT "wishlists_pkey" PRIMARY KEY (id),
    CONSTRAINT "wishlists_user_id_product_id_key" UNIQUE (user_id, product_id)
);
