-- ================================================================
-- Index: idx_products_category on catalog.products
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_products_category ON catalog.products USING btree (category_id);
