-- ================================================================
-- Index: idx_products_brand on catalog.products
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_products_brand ON catalog.products USING btree (brand_id);
