-- ================================================================
-- Index: idx_products_active on catalog.products
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_products_active ON catalog.products USING btree (is_active, published_at DESC) WHERE ((is_active = true) AND (deleted_at IS NULL));
