-- ================================================================
-- Index: idx_products_featured on catalog.products
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_products_featured ON catalog.products USING btree (is_featured) WHERE (is_featured = true);
