-- ================================================================
-- Index UNIQUE: products_sku_key on catalog.products
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX products_sku_key ON catalog.products USING btree (sku);
