-- ================================================================
-- Index: idx_variants_sku on catalog.product_variants
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_variants_sku ON catalog.product_variants USING btree (sku);
