-- ================================================================
-- Index UNIQUE: product_variants_sku_key on catalog.product_variants
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX product_variants_sku_key ON catalog.product_variants USING btree (sku);
