-- ================================================================
-- Sequence: catalog.attribute_types_id_seq
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE SEQUENCE "catalog"."attribute_types_id_seq";
