-- ================================================================
-- Sequence: catalog.product_images_id_seq
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE SEQUENCE "catalog"."product_images_id_seq";
