-- ================================================================
-- Index UNIQUE: coupons_code_key on commerce.coupons
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX coupons_code_key ON commerce.coupons USING btree (code);
