-- ================================================================
-- Index: idx_order_items_order on commerce.order_items
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_order_items_order ON commerce.order_items USING btree (order_id);
