-- ================================================================
-- Index UNIQUE: attribute_types_name_key on catalog.attribute_types
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX attribute_types_name_key ON catalog.attribute_types USING btree (name);
