-- ================================================================
-- Sequence: commerce.order_items_id_seq
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE SEQUENCE "commerce"."order_items_id_seq";
