-- ================================================================
-- Index UNIQUE: wishlists_user_id_product_id_key on commerce.wishlists
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX wishlists_user_id_product_id_key ON commerce.wishlists USING btree (user_id, product_id);
