-- ================================================================
-- Table: identity.addresses
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "identity"."addresses" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "user_id" uuid NOT NULL,
    "type" address_type NOT NULL DEFAULT 'both'::address_type,
    "label" character varying(50),
    "recipient_name" character varying(200) NOT NULL,
    "phone" character varying(20),
    "address_line1" character varying(255) NOT NULL,
    "address_line2" character varying(255),
    "city" character varying(100) NOT NULL,
    "state" character varying(100),
    "postal_code" character varying(20) NOT NULL,
    "country_code" character(2) NOT NULL DEFAULT 'US'::bpchar,
    "is_default" boolean NOT NULL DEFAULT false,
    "latitude" numeric(10,7),
    "longitude" numeric(10,7),
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES identity.users(id) ON DELETE CASCADE,
    CONSTRAINT "addresses_pkey" PRIMARY KEY (id)
);
