-- ================================================================
-- Table: identity.roles
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "identity"."roles" (
    "id" smallint NOT NULL DEFAULT nextval('identity.roles_id_seq'::regclass),
    "name" character varying(50) NOT NULL,
    "description" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "roles_pkey" PRIMARY KEY (id),
    CONSTRAINT "roles_name_key" UNIQUE (name)
);
