-- ================================================================
-- Table: identity.users
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE TABLE "identity"."users" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "role_id" smallint NOT NULL DEFAULT 1,
    "email" citext NOT NULL,
    "phone" character varying(20),
    "password_hash" text NOT NULL,
    "first_name" character varying(100) NOT NULL,
    "last_name" character varying(100) NOT NULL,
    "gender" gender_type,
    "date_of_birth" date,
    "avatar_url" text,
    "is_verified" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "last_login_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    "deleted_at" timestamp with time zone,
    CONSTRAINT "chk_email_format" CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::citext),
    CONSTRAINT "users_role_id_fkey" FOREIGN KEY (role_id) REFERENCES identity.roles(id),
    CONSTRAINT "users_pkey" PRIMARY KEY (id),
    CONSTRAINT "users_email_key" UNIQUE (email),
    CONSTRAINT "users_phone_key" UNIQUE (phone)
);
