-- ================================================================
-- Index: idx_payments_gateway on commerce.payments
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_payments_gateway ON commerce.payments USING btree (gateway_txn_id);
