-- ================================================================
-- Index: idx_payments_status on commerce.payments
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_payments_status ON commerce.payments USING btree (status);
