-- ================================================================
-- Index: idx_payments_order on commerce.payments
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE INDEX idx_payments_order ON commerce.payments USING btree (order_id);
