-- ================================================================
-- Index UNIQUE: brands_name_key on catalog.brands
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX brands_name_key ON catalog.brands USING btree (name);
