-- ================================================================
-- Index UNIQUE: brands_slug_key on catalog.brands
-- Generated by pgStudio · 2026-03-07T12:03:06.362Z
-- ================================================================


CREATE UNIQUE INDEX brands_slug_key ON catalog.brands USING btree (slug);
